import sqlmodel

"""

Revision ID: 212ea4c9f7f0
Revises: c52e18da0bd8
Create Date: 2025-06-27 09:33:30.615342

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "212ea4c9f7f0"
down_revision: Union[str, None] = "c52e18da0bd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("deleted_at", sa.Date(), nullable=True))
    op.alter_column(
        "user",
        "bio",
        existing_type=sa.VARCHAR(length=1000),
        type_=sqlmodel.sql.sqltypes.AutoString(length=200),
        existing_nullable=True,
    )
    op.drop_column("user", "deletion_scheduled_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "deletion_scheduled_at", sa.DATE(), autoincrement=False, nullable=True
        ),
    )
    op.alter_column(
        "user",
        "bio",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=200),
        type_=sa.VARCHAR(length=1000),
        existing_nullable=True,
    )
    op.drop_column("user", "deleted_at")
    # ### end Alembic commands ###
