"""add deletion_scheduled_at field to user table

Revision ID: 4043fd2c4115
Revises: 9c35ea001e95
Create Date: 2025-06-24 14:35:16.091584

"""
from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "4043fd2c4115"
down_revision: Union[str, None] = "9c35ea001e95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
