"""

Revision ID: 74937651b33f
Revises: dd22a682acf0
Create Date: 2025-06-25 18:12:32.386921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74937651b33f"
down_revision: Union[str, None] = "dd22a682acf0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "follow",
        "created_at",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "follow",
        "updated_at",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    
    # Add columns as nullable first
    op.add_column("photo", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("photo", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("updated_at", sa.DateTime(), nullable=True))
    
    # Set default values for existing records
    op.execute("UPDATE photo SET created_at = NOW(), updated_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE photo SET updated_at = NOW() WHERE updated_at IS NULL")
    op.execute("UPDATE \"user\" SET created_at = NOW(), updated_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE \"user\" SET updated_at = NOW() WHERE updated_at IS NULL")
    
    # Make columns NOT NULL
    op.alter_column("photo", "created_at", nullable=False)
    op.alter_column("photo", "updated_at", nullable=False)
    op.alter_column("user", "created_at", nullable=False)
    op.alter_column("user", "updated_at", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_column("photo", "updated_at")
    op.drop_column("photo", "created_at")
    op.alter_column(
        "follow",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    op.alter_column(
        "follow",
        "created_at",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
