"""add_deletion_scheduled_at_field

Revision ID: 9c35ea001e95
Revises: 65e9b07345b7
Create Date: 2025-06-24 14:32:21.854225

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c35ea001e95"
down_revision: Union[str, None] = "65e9b07345b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("deletion_scheduled_at", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "deletion_scheduled_at")
    # ### end Alembic commands ###
