"""Revision ID: c74db799c2dd
Revises: b6bcba1eb2c0
Create Date: 2025-06-28 15:21:19.804000

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c74db799c2dd"
down_revision: Union[str, None] = "b6bcba1eb2c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "name", existing_type=sa.VARCHAR(length=255), nullable=True)
    # ### end Alembic commands ###
