"""ensure_is_active_defaults_to_true

Revision ID: ccaff8878f75
Revises: 4043fd2c4115
Create Date: 2025-06-24 15:33:32.741843

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ccaff8878f75"
down_revision: Union[str, None] = "4043fd2c4115"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_verified column with default True and make it NOT NULL
    op.add_column("user", sa.Column("is_verified", sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_verified")
    # ### end Alembic commands ###
